#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Values persist outside the repo so nothing lands in git. Re-runs pick them up.
ENV_FILE="${ENV_FILE:-$HOME/.config/recipe-app/store-accounts.env}"
mkdir -p "$(dirname "$ENV_FILE")"

GCP_PROJECT="recipe-app-508817"
# The owning account comes from gcloud so no email lands in the public repo.
GCP_ACCOUNT="${GCP_ACCOUNT:-$(gcloud config get-value account 2>/dev/null || true)}"
GCP_ACCOUNT="${GCP_ACCOUNT:-the Google account that owns $GCP_PROJECT}"
ISSUE=3

# Every prompt reads from the keyboard. Without a terminal on stdin (e.g. run
# through Claude Code's "!" prefix) each prompt returns at once and the whole
# wizard falls through, so refuse to start.
if [[ ! -t 0 ]]; then
  printf 'This wizard needs an interactive terminal. Open a WSL terminal and run:\n' >&2
  printf '  cd %s && bash scripts/wizard-store-accounts.sh\n' "$(cd "$(dirname "$0")/.." && pwd)" >&2
  exit 1
fi

# Override of the library's open_url: explorer.exe exits 1 even when it opens
# the page, which made the library warn on every URL under WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if   command -v wslview      >/dev/null 2>&1; then wslview "$url" >/dev/null 2>&1 || true
  elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url" >/dev/null 2>&1 || true
  else warn "couldn't open a browser; visit it manually: $url"; fi
  note "If no tab opened, copy the URL above into your browser."
}

banner "Store accounts + Firebase (issues #3 and #15)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Apple: check the Apple Account"
say "Apple approval can take days, so Apple goes first."
say "Enrolment as an individual needs an Apple Account with two-factor"
say "authentication on, and the name on it must be your legal name: it becomes"
say "the seller name on the App Store."
open_url "https://account.apple.com/"
step "Sign in with the Apple Account you want to own the app."
step "Check the name is your legal first and last name (no alias, no company)."
step "Under Sign-In and Security, check two-factor authentication is on."
pause "Press Enter when the account is ready"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Apple: enrol in the Developer Program as an individual"
say "Costs 99 USD per year (charged in local currency)."
open_url "https://developer.apple.com/programs/enroll/"
step "Click 'Start your enrollment' and sign in with the same Apple Account."
step "Entity type: choose Individual / Sole Proprietor (no D-U-N-S needed)."
step "Enter your legal name, address and phone exactly as on your ID."
step "Accept the agreement, then complete the purchase."
note "Apple may ask for a government ID photo. If the web flow sends you to the"
note "Apple Developer app, that needs an iPhone, iPad or Mac signed in to the"
note "same Apple Account. I couldn't check which path your account gets."
warn "Approval is not instant. Carry on with the next stages while you wait."
pause "Press Enter once the purchase is submitted"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Play: create the developer account"
say "One-time 25 USD registration fee."
open_url "https://play.google.com/console/signup"
step "Sign in with the Google account that should own the Play listing."
step "Account type: choose 'Yourself' (personal account)."
step "Fill in developer name (shown on Play), legal name, address, contact"
step "email and phone. Read what Play says will be shown publicly: for an app"
step "that earns money, Play displays more of your contact details."
step "Pay the registration fee."
warn "A new personal account must run a closed test (12+ testers, 14 days) before"
warn "production access. That is tracked by the compliance research (#13)."
pause "Press Enter once the fee is paid"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Play: finish the verifications"
say "Play Console home shows a list of verification tasks. Do every one it"
say "lists; typically identity (government ID), contact phone and email, and"
say "for personal accounts access to a real Android device via the Play"
say "Console mobile app."
open_url "https://play.google.com/console"
step "Work through each verification task on the home page."
note "Identity review can take a few days. You can re-run this wizard later;"
note "it remembers what you already entered."
pause "Press Enter when the verifications are submitted"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Domain: buy the product .app domain on Cloudflare"
say "The bundle id is derived from this domain (app.<name>, decided on #2), and"
say "the privacy policy, Terms of Use and account deletion page will live on it."
say "A .app domain costs about 14 USD per year at Cloudflare (sold at cost)."
ask APP_DOMAIN "Domain to buy: type panwise.app (or Enter to skip):"
if [[ -n "$APP_DOMAIN" ]]; then
  open_url "https://dash.cloudflare.com/?to=/:account/domains/register"
  step "Sign in or create a Cloudflare account (turn on two-factor authentication)."
  step "Search for $APP_DOMAIN and check the price shown is the normal .app price,"
  step "not a premium one. Stop and tell Claude if it is premium or taken."
  step "Buy it with auto-renew ON. WHOIS redaction is included for free."
  note "Email forwarding (support@$APP_DOMAIN → your Gmail) is set up later, under"
  note "Email → Email Routing, once the store listing needs a support address."
  if confirm "Is $APP_DOMAIN registered to your Cloudflare account?"; then
    write_env APP_DOMAIN "$APP_DOMAIN"
  else
    SKIPPED+=("Buy $APP_DOMAIN on Cloudflare Registrar")
  fi
else
  SKIPPED+=("Buy the product .app domain (panwise.app, see issue #2)")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Firebase: add Firebase to $GCP_PROJECT"
say "The API call to add Firebase was refused for $GCP_ACCOUNT even though it"
say "owns the project. The likely cause is that the Firebase terms have not"
say "been accepted for that account, which only happens in the console."
open_url "https://console.firebase.google.com/"
step "Sign in as $GCP_ACCOUNT (check the avatar, top right)."
step "Start creating a project, then pick 'Add Firebase to Google Cloud project'"
step "(a link near the bottom of the first step) and select $GCP_PROJECT."
step "Accept the Firebase terms when asked."
step "Google Analytics: turn it OFF for now. The analytics choice is still open"
step "on the map and it can be enabled later."
step "Do NOT create a Firestore database in the console: it already exists in"
step "me-west1."
pause "Press Enter when the console shows the project overview"

if command -v gcloud >/dev/null 2>&1; then
  _tok=$(gcloud auth print-access-token --account "$GCP_ACCOUNT" 2>/dev/null || true)
  _code=$(curl -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $_tok" -H "x-goog-user-project: $GCP_PROJECT" \
    "https://firebase.googleapis.com/v1beta1/projects/$GCP_PROJECT" || true)
  if [[ "$_code" == "200" ]]; then
    printf '  %s✓ verified%s Firebase is on %s\n' "$GREEN" "$RESET" "$GCP_PROJECT"
    write_env FIREBASE_ADDED "yes"
  else
    warn "Firebase not visible on $GCP_PROJECT yet (HTTP $_code)."
    SKIPPED+=("Add Firebase to $GCP_PROJECT in the Firebase console")
    pause "Press Enter to continue anyway"
  fi
else
  warn "gcloud not found, so this wizard can't verify the step."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Firebase: enable Google and Apple sign-in"
say "Enabling Google here also creates the OAuth client for you."
open_url "https://console.firebase.google.com/project/$GCP_PROJECT/authentication/providers"
step "If you see 'Get started', click it."
step "Sign-in method → Add new provider → Google → Enable."
step "Pick a support email, set the public-facing project name, Save."
step "Add new provider → Apple → Enable → Save. Leave the Services ID and the"
step "OAuth code flow fields empty: they need the Apple Developer account and"
step "get filled in once enrolment is approved."
note "If the console won't save Apple without those fields, skip Apple for now."
if confirm "Is the Google provider enabled?"; then write_env AUTH_GOOGLE_ENABLED "yes"
else SKIPPED+=("Enable the Google sign-in provider in Firebase Auth"); fi
if confirm "Is the Apple provider enabled?"; then write_env AUTH_APPLE_ENABLED "yes"
else SKIPPED+=("Enable the Apple sign-in provider in Firebase Auth (after Apple approval)"); fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Apple: record the Team ID"
say "Only available once Apple has approved the enrolment (you get an email)."
open_url "https://developer.apple.com/account"
step "Scroll to 'Membership details' and copy the Team ID (10 characters)."
note "Not approved yet? Leave it empty and re-run this wizard later."
ask APPLE_TEAM_ID "Paste the Team ID (or Enter to skip):"
if [[ -n "$APPLE_TEAM_ID" ]]; then write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
else SKIPPED+=("Apple Team ID (re-run after Apple approves the enrolment)"); fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Google Play: record the developer account ID"
open_url "https://play.google.com/console"
step "The ID is the long number in the address bar:"
step "play.google.com/console/u/0/developers/<THIS NUMBER>/..."
step "It is also shown under Settings → Developer account → Account details."
ask PLAY_DEVELOPER_ID "Paste the developer account ID (or Enter to skip):"
if [[ -n "$PLAY_DEVELOPER_ID" ]]; then write_env PLAY_DEVELOPER_ID "$PLAY_DEVELOPER_ID"
else SKIPPED+=("Play developer account ID"); fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Record the ids on issue #$ISSUE"
if [[ -n "${APPLE_TEAM_ID:-}" && -n "${PLAY_DEVELOPER_ID:-}" ]]; then
  say "Both ids captured. Neither is a secret, and the repo is public."
  say "  Apple Team ID:             $APPLE_TEAM_ID"
  say "  Play developer account ID: $PLAY_DEVELOPER_ID"
  if confirm "Post these as a comment on issue #$ISSUE?"; then
    if gh issue comment "$ISSUE" --body "Accounts active. Apple Team ID: \`$APPLE_TEAM_ID\`. Play developer account ID: \`$PLAY_DEVELOPER_ID\`." >/dev/null 2>&1; then
      printf '  %s✓ commented%s on issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
    else
      SKIPPED+=("Comment the ids on issue #$ISSUE (gh failed)")
    fi
  else
    SKIPPED+=("Comment the ids on issue #$ISSUE")
  fi
else
  warn "One or both ids are missing, so nothing is posted. Re-run when you have them."
fi

finish
